-- Tables the game owns, as opposed to the ones a round set fills in.
--
-- Kept apart from answers.sql for that reason: answers.sql is generated by
-- make_rounds.py, gitignored (it is the answer key, and this is a public repo)
-- and re-pushed on every regeneration, while this file is hand-written, tracked,
-- and pushed once per database. Folding the two together would mean a table of
-- player scores whose definition only existed on whichever laptop last built a
-- round set.
--
-- Idempotent, so `task schema:{local,stage,prod}:push` is safe to re-run.

-- One row per player per round per date: the record of a daily play, and the
-- leaderboard's entire storage. Both boards are one query over this.
--
-- It exists because scoring on its own is stateless: with no record of a play, a
-- client can score the same round over and over and keep the best number, and a
-- board on top of that ranks whoever re-guessed most, not who guessed best.
CREATE TABLE IF NOT EXISTS plays (
  -- The calendar date of the round set played, YYYY-MM-DD. The date itself
  -- rather than the day number, so a re-epoch or an off-by-one in dayNumber()
  -- cannot silently re-map history. `Guessr #N` stays a display label derived
  -- from it.
  date TEXT NOT NULL,
  -- Opaque, minted into localStorage on first play. NOT the handle: two players
  -- who both type "Jason" are two players, and keying on the name would read the
  -- second one's play as a replay of the first's and drop it. NOT the IP either
  -- -- NAT collapses a household into one player, CGNAT splits one phone into
  -- several across a day, and an address stored beside a typed name turns a
  -- storage disclosure into a personal-data one.
  player_id TEXT NOT NULL,
  image TEXT NOT NULL,
  -- Both, so a replay can be answered with the score that was actually recorded
  -- rather than a fresh distance beside a stale point total.
  km REAL NOT NULL,
  points INTEGER NOT NULL,
  -- A display label, nullable: a browser that cannot keep localStorage has no
  -- name to send, and a play still belongs on the board without one.
  handle TEXT,
  played_at TEXT NOT NULL DEFAULT (datetime('now')),
  -- First write wins, which is the whole point of the table. As the primary key
  -- rather than a separate unique index, so the uniqueness and the lookup that
  -- serves a replay are the same structure.
  PRIMARY KEY (date, player_id, image)
);

-- The daily board is the top of one date; the monthly board sums a date prefix.
-- Both start from a date scan, so one index over (date, points) serves them.
CREATE INDEX IF NOT EXISTS plays_by_date_points ON plays (date, points DESC);

-- The name on a board row is a different access path, which the index above
-- cannot serve: it seeks a player's most recent non-null handle across every
-- date they have played, so there is no date to scan from. Without an index on
-- player_id alone that seek is a full table scan, once per board row -- and the
-- boards are polled continuously to feed the stream overlay, on two separate
-- cache keys that the 60s response cache cannot collapse. That came to ~8.7M
-- rows read a day against a few hundred rows of stored data -- inside the Workers
-- Paid allowance, so the cost of it was wasted work rather than money, but the
-- ratio is the thing to notice: reads scale with plays x board rows x poll rate,
-- so it grows with the game while the data does not.
-- test_leaderboard.mjs asserts the query plan still uses it.
CREATE INDEX IF NOT EXISTS plays_by_player_recent ON plays (player_id, played_at);
